[variables]
NIXPACKS_NO_CACHE = "1"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npx prisma generate"]

[start]
cmd = "cd backend && npm start"

